// packages/frontend-svelte/src/pages/CrossProductPage.svelte
<script>
  import { crossProduct, generateVector } from '@matrices/common';

  import Matrix from '../components/matrix/Matrix.svelte';
  import Equal from '../components/svg/Equal.svelte';
import Multiply from '../components/svg/Multiply.svelte';
  import { useMatrix } from '../store/useMatrix';

  import OperationPage from './OperationPage.svelte';

  let { cells: cells1, props: props1 } = useMatrix({
    unresizable: true,
    defaultCells: [generateVector(3)]
  });
  let { cells: cells2, props: props2 } = useMatrix({
    unresizable: true,
    defaultCells: [generateVector(3)]
  });

  let {
    cells: productCells,
    props: productProps,
    clear: clearProduct
  } = useMatrix({ readonly: true, unresizable: true, defaultCells: [generateVector(3)] });

  $: {
    const [u] = $cells1;
    const [v] = $cells2;
    const result = crossProduct(u, v);
    if (result.ok) {
      productCells.set([result.value]);
    } else {
      clearProduct();
    }
  }
</script>

<OperationPage>
  <Matrix {...$props1}>
    <svelte:fragment slot="label">u</svelte:fragment>
  </Matrix>
  <Multiply />
  <Matrix {...$props2}>
    <svelte:fragment slot="label">v</svelte:fragment>
  </Matrix>
  <Equal />
  <Matrix {...$productProps}>
    <svelte:fragment slot="label">u×v</svelte:fragment>
  </Matrix>
</OperationPage>

// packages/frontend-react/src/pages/CrossProductPage.tsx
import { crossProduct, generateVector } from '@matrices/common';
import React, { useEffect } from 'react';

import { Equal } from '../components/svg/Equal';
import { Multiply as Cross } from '../components/svg/Multiply';
import { Matrix } from '../matrix/Matrix';

import { useMatrix } from '../matrix/useMatrix';

import { OperationPage } from './OperationPage';

export const CrossProductPage: React.VFC = () => {
  const vector1 = useMatrix({
    label: 'u',
    unresizable: true,
    defaultCells: [generateVector(3, () => null)]
  });

  const vector2 = useMatrix({
    label: 'v',
    unresizable: true,
    defaultCells: [generateVector(3, () => null)]
  });

  const product = useMatrix({
    label: 'u×v',
    unresizable: true,
    readonly: true,
    defaultCells: [generateVector(3, () => null)]
  });

  const { setCells: setProductCells, clear: clearProduct } = product;
  useEffect(() => {
    const [v1] = vector1.cells;
    const [v2] = vector2.cells;

    const result = crossProduct(v1, v2);
    if (result.ok) {
      setProductCells([result.value]);
    } else {
      clearProduct();
    }
  }, [vector1.cells, vector2.cells, setProductCells, clearProduct]);

  return (
    <OperationPage>
      <Matrix {...vector1.toProps()} />
      <Cross />
      <Matrix {...vector2.toProps()} />
      <Equal />
      <Matrix {...product.toProps()} />
    </OperationPage>
  );
};
