// packages/frontend-angular/src/app/pages/matrix-multiplication-page/matrix-multiplication-page.component.ts
import { Component, OnInit } from '@angular/core';
import { multiplyMatrices } from '@matrices/common';
import { zip } from 'rxjs';

import { Matrix } from 'src/Matrix';

@Component({
  selector: 'app-matrix-multiplication-page',
  templateUrl: './matrix-multiplication-page.component.html',
  styles: []
})
export class MatrixMultiplicationPageComponent implements OnInit {
  matrix1 = new Matrix();
  matrix2 = new Matrix();
  product = new Matrix({ unresizable: true, readonly: true });

  constructor() {}

  ngOnInit() {
    //Listen to the cells of both observables, and update cell accordingly.
    zip(this.matrix1.cellsObserver, this.matrix2.cellsObserver).subscribe(([cells1, cells2]) => {
      const result = multiplyMatrices(cells1, cells2);
      if (result.ok) {
        this.product.cells = result.value;
      } else {
        this.product.clear();
      }
    });
  }
}

<app-operation-page>

  <app-matrix [m]="matrix1">
    <ng-container label>A</ng-container>
  </app-matrix>

  <app-multiply></app-multiply>

  <app-matrix [m]="matrix2">
    <ng-container label>B</ng-container>
  </app-matrix>

  <app-equal></app-equal>

  <app-matrix [m]="product">
    <ng-container label>AB</ng-container>
  </app-matrix>

</app-operation-page>

// packages/frontend-react/src/pages/MatrixMultiplicationPage.tsx
import React, { useEffect } from 'react';
import { multiplyMatrices } from '@matrices/common';

import { Equal } from '../components/svg/Equal';
import { Multiply } from '../components/svg/Multiply';
import { Matrix } from '../matrix/Matrix';
import { useMatrix } from '../matrix/useMatrix';

import { OperationPage } from './OperationPage';

/**
 * The page in which matrices can be multiplied, rendered in path /matrix/product.
 */
export const MatrixMultiplicationPage: React.VFC = () => {
  const matrix1 = useMatrix({ label: 'A' });
  const matrix2 = useMatrix({ label: 'B' });
  const product = useMatrix({ label: 'AB', readonly: true, unresizable: true });

  const { setCells: setProductCells, clear: clearProduct } = product;
  useEffect(() => {
    const result = multiplyMatrices(matrix1.cells, matrix2.cells);
    if (result.ok) {
      setProductCells(result.value);
    } else {
      clearProduct();
    }
  }, [matrix1.cells, matrix2.cells, setProductCells, clearProduct]);

  return (
    <OperationPage>
      <Matrix {...matrix1.toProps()} />
      <Multiply />
      <Matrix {...matrix2.toProps()} />
      <Equal />
      <Matrix {...product.toProps()} />
    </OperationPage>
  );
};
