// packages/frontend-svelte/src/pages/MatrixAdditionPage.svelte
<script>
  import { addMatrices } from '@matrices/common';

  import Matrix from '../components/matrix/Matrix.svelte';
  import Equal from '../components/svg/Equal.svelte';
  import Plus from '../components/svg/Plus.svelte';
  import { useMatrix } from '../store/useMatrix';

  import OperationPage from './OperationPage.svelte';

  let { cells: cells1, props: props1 } = useMatrix();
  let { cells: cells2, props: props2 } = useMatrix();

  let {
    cells: sumCells,
    props: sumProps,
    clear: clearSum
  } = useMatrix({ readonly: true, unresizable: true });

  $: {
    const result = addMatrices($cells1, $cells2);
    if (result.ok) {
      sumCells.set(result.value);
    } else {
      clearSum();
    }
  }
</script>

<OperationPage>
  <Matrix {...$props1}>
    <svelte:fragment slot="label">A</svelte:fragment>
  </Matrix>
  <Plus />
  <Matrix {...$props2}>
    <svelte:fragment slot="label">B</svelte:fragment>
  </Matrix>
  <Equal />
  <Matrix {...$sumProps}>
    <svelte:fragment slot="label">A+B</svelte:fragment>
  </Matrix>
</OperationPage>

// packages/frontend-react/src/pages/MatrixAdditionPage.tsx
import React, { useEffect } from 'react';
import { addMatrices } from '@matrices/common';

import { Equal } from '../components/svg/Equal';
import { Plus } from '../components/svg/Plus';
import { Matrix } from '../matrix/Matrix';
import { useMatrix } from '../matrix/useMatrix';

import { OperationPage } from './OperationPage';

/**
 * The page in which matrices can be summed up, rendered in path /matrix/sum.
 */
export const MatrixAdditionPage: React.VFC = () => {
  const matrix1 = useMatrix({ label: 'A' });
  const matrix2 = useMatrix({ label: 'B' });
  const sum = useMatrix({ label: 'A+B', readonly: true, unresizable: true });

  const { setCells: setSumCells, clear: clearSum } = sum;
  useEffect(() => {
    const result = addMatrices(matrix1.cells, matrix2.cells);
    if (result.ok) {
      setSumCells(result.value);
    } else {
      clearSum();
    }
  }, [matrix1.cells, matrix2.cells, setSumCells, clearSum]);

  return (
    <OperationPage>
      <Matrix {...matrix1.toProps()} />
      <Plus />
      <Matrix {...matrix2.toProps()} />
      <Equal />
      <Matrix {...sum.toProps()} />
    </OperationPage>
  );
};
