// packages/frontend-angular/src/app/pages/matrix-addition-page/matrix-addition-page.component.ts
import { Component, OnInit } from '@angular/core';
import { addMatrices } from '@matrices/common';
import { zip } from 'rxjs';

import { Matrix } from 'src/Matrix';

@Component({
  selector: 'app-matrix-addition-page',
  templateUrl: './matrix-addition-page.component.html',
  styles: []
})
export class MatrixAdditionPageComponent implements OnInit {
  matrix1 = new Matrix();
  matrix2 = new Matrix();
  sum = new Matrix({ unresizable: true, readonly: true });

  constructor() {}

  ngOnInit() {
    //Listen to the cells of both observables, and update cell accordingly.
    zip(this.matrix1.cellsObserver, this.matrix2.cellsObserver).subscribe(([cells1, cells2]) => {
      const result = addMatrices(cells1, cells2);
      if (result.ok) {
        this.sum.cells = result.value;
      } else {
        this.sum.clear();
      }
    });
  }
}

<app-operation-page>
  
  <app-matrix [m]="matrix1">
    <ng-container label>A</ng-container>
  </app-matrix>

  <app-plus></app-plus>

  <app-matrix [m]="matrix2">
    <ng-container label>B</ng-container>
  </app-matrix>

  <app-equal></app-equal>

  <app-matrix [m]="sum">
    <ng-container label>A+B</ng-container>
  </app-matrix>

</app-operation-page>

// packages/frontend-react/src/pages/MatrixAdditionPage.tsx
import React, { useEffect } from 'react';
import { addMatrices } from '@matrices/common';

import { Equal } from '../components/svg/Equal';
import { Plus } from '../components/svg/Plus';
import { Matrix } from '../matrix/Matrix';
import { useMatrix } from '../matrix/useMatrix';

import { OperationPage } from './OperationPage';

/**
 * The page in which matrices can be summed up, rendered in path /matrix/sum.
 */
export const MatrixAdditionPage: React.VFC = () => {
  const matrix1 = useMatrix({ label: 'A' });
  const matrix2 = useMatrix({ label: 'B' });
  const sum = useMatrix({ label: 'A+B', readonly: true, unresizable: true });

  const { setCells: setSumCells, clear: clearSum } = sum;
  useEffect(() => {
    const result = addMatrices(matrix1.cells, matrix2.cells);
    if (result.ok) {
      setSumCells(result.value);
    } else {
      clearSum();
    }
  }, [matrix1.cells, matrix2.cells, setSumCells, clearSum]);

  return (
    <OperationPage>
      <Matrix {...matrix1.toProps()} />
      <Plus />
      <Matrix {...matrix2.toProps()} />
      <Equal />
      <Matrix {...sum.toProps()} />
    </OperationPage>
  );
};
