// packages/frontend-svelte/src/pages/MatrixTransposePage.svelte
<script>
  import { transpose } from '@matrices/common';

  import Matrix from '../components/matrix/Matrix.svelte';
  import RightArrow from '../components/svg/RightArrow.svelte';
  import { useMatrix } from '../store/useMatrix';

  import OperationPage from './OperationPage.svelte';

  let { cells: cells1, props: props1 } = useMatrix();

  let {
    cells: transposeCells,
    props: transposeProps,
    clear: clearTranspose
  } = useMatrix({ readonly: true, unresizable: true });

  $: {
    const result = transpose($cells1);
    if (result.ok) {
      transposeCells.set(result.result);
    } else {
      clearTranspose();
    }
  }
</script>

<OperationPage>
  <Matrix {...$props1}>
    <svelte:fragment slot="label">A</svelte:fragment>
  </Matrix>
  <RightArrow />
  <Matrix {...$transposeProps}>
    <svelte:fragment slot="label">A<sup>t</sup></svelte:fragment>
  </Matrix>
</OperationPage>

// packages/frontend-react/src/pages/MatrixTransposePage.tsx
import React, { useEffect } from "react";
import { createUseStyles } from "react-jss";
import { transpose } from "@matrices/common";


import { Equal } from "../components/svg/Equal";
import { Matrix } from "../matrix/Matrix";
import { useMatrix } from "../matrix/useMatrix";
import { OperationPage } from './OperationPage';

const useStyles = createUseStyles({
  inputMatrix: {
    alignSelf: "center",
  },
});

/**
 * Page in which the transpose of a matrix can be calulated. Rendered at /matrix/transpose.
 */
export const MatrixTransposePage: React.VFC = () => {
  const matrix = useMatrix({ label: "A" });
  const tranposed = useMatrix({ label: <span>A<sup>t</sup></span>, readonly: true });

  useEffect(() => {
    const result = transpose(matrix.cells);
    if (result) {
      tranposed.setCells(result);
    } else {
      tranposed.clear();
    }
  }, [matrix.cells, tranposed.setCells, tranposed.clear]);

  const { inputMatrix } = useStyles();

  return (
    <OperationPage>
      <Matrix {...matrix.toProps()} className={inputMatrix} />
      <Equal />
      <Matrix {...tranposed.toProps()} />
    </OperationPage>

  );
};
