// packages/frontend-react/src/pages/DotProductPage.tsx
import { dotProduct, generateVector } from '@matrices/common';
import React, { useEffect } from 'react';

import { Dot } from '../components/svg/Dot';

import { Equal } from '../components/svg/Equal';
import { Matrix } from '../matrix/Matrix';

import { useMatrix } from '../matrix/useMatrix';

import { OperationPage } from './OperationPage';

export const DotProductPage: React.VFC = () => {
  const vector1 = useMatrix({
    label: 'u',
    unresizable: true,
    defaultCells: [generateVector(3, () => undefined)]
  })

  const vector2 = useMatrix({
    label: 'v',
    unresizable: true,
    defaultCells: [generateVector(3, () => undefined)]
  })

  const product = useMatrix({
    label: 'u·v',
    readonly: true,
    unresizable: true,
    defaultCells: [[undefined]]
  })

  const { setCells: setProductCells, clear: clearProduct } = product;
  useEffect(() => {
    const [v1] = vector1.cells;
    const [v2] = vector2.cells;

    const result = dotProduct(v1, v2);
    if (result.ok) {
      setProductCells([[result.result]]);
    }
    else {
      clearProduct();
    }
  }, [vector1.cells, vector2.cells, clearProduct, setProductCells])

  return (
    <OperationPage>
      <Matrix {...vector1.toProps()} />
      <Dot />
      <Matrix {...vector2.toProps()} />
      <Equal />
      <Matrix {...product.toProps()} />
    </OperationPage>
  )
};

// packages/frontend-svelte/src/pages/DotProductPage.svelte
<script>
  import { dotProduct, generateVector } from '@matrices/common';

  import Matrix from '../components/matrix/Matrix.svelte';
  import Dot from '../components/svg/Dot.svelte';
  import Equal from '../components/svg/Equal.svelte';
  import { useMatrix } from '../store/useMatrix';

  import OperationPage from './OperationPage.svelte';

  let { cells: cells1, props: props1 } = useMatrix({
    unresizable: true,
    defaultCells: [generateVector(3, () => undefined)]
  });
  let { cells: cells2, props: props2 } = useMatrix({
    unresizable: true,
    defaultCells: [generateVector(3, () => undefined)]
  });

  let {
    cells: productCells,
    props: productProps,
    clear: clearproduct
  } = useMatrix({ readonly: true, unresizable: true, defaultCells: [[undefined]] });

  $: {
    const [u] = $cells1;
    const [v] = $cells2;
    const result = dotProduct(u, v);
    if (result.ok) {
      productCells.set([[result.result]]);
    } else {
      clearproduct();
    }
  }
</script>

<OperationPage>
  <Matrix {...$props1}>
    <svelte:fragment slot="label">u</svelte:fragment>
  </Matrix>
  <Dot />
  <Matrix {...$props2}>
    <svelte:fragment slot="label">v</svelte:fragment>
  </Matrix>
  <Equal />
  <Matrix {...$productProps}>
    <svelte:fragment slot="label">u·v</svelte:fragment>
  </Matrix>
</OperationPage>
