// packages/frontend-vue/src/components/TopBar.vue
<template>
  <div class="bar">
    <span class="text">
      <h1>
        <router-link to="/">Coolest Matrices</router-link>
      </h1>
      <span v-if="!!pagename">/</span>
      <span v-if="!!pagename">{{ pagename }}</span>
    </span>
    <a href="https://github.com/NitzanHen/matrices">
      <Github class="github" />
    </a>
  </div>
</template>

<script lang='ts'>
import { defineComponent } from "vue";
import Github from "./svg/Github.vue";

export default defineComponent({
  name: 'top-bar',
  components: {
    Github,
  },
  props: {
    pagename: String
  },
  setup(props) {
    return props;
  }
})
</script>

<style scoped>
.bar {
  background-color: var(--background-dark);
  color: white;
  padding: 16px;
  box-shadow: 0px 3px 9px 0px #00000050;

  display: flex;
  justify-content: space-between;
  align-items: center;
}

.text > h1 {
  display: inline;
}
.text > :not(h1) {
  font-size: 22px;
  letter-spacing: 2;
}
.text > :not(:last-child) {
  margin-right: 8px;
}

.github {
  width: 2em;
  height: 2em;
  fill: white;
  display: block;
}
</style>

// packages/frontend-react/src/components/TopBar.tsx
import React from 'react';
import { createUseStyles } from 'react-jss';
import { Link as RouterLink } from 'react-router-dom';

import { Github } from './svg/Github';

const useStyles = createUseStyles(
  {
    root: {
      backgroundColor: 'var(--background-dark)',
      color: 'white',
      padding: 16,
      boxShadow: '0px 3px 9px 0px #00000050',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center'
    },
    github: {
      width: '2em',
      height: '2em',
      fill: 'white',
      display: 'block'
    },
    text: {

      '& > h1': {
        display: 'inline'
      },

      '& > *:not(h1)': {
        fontSize: 22,
        letterSpacing: 2,
      },

      '& > *:not(:last-child)': {
        marginRight: 8
      }
    },
  },
  { name: 'top-bar' }
);

interface TopBarProps {
  page?: string;
}

export const TopBar: React.VFC<TopBarProps> = ({ page }) => {
  const classes = useStyles();

  return (
    <div className={classes.root}>
      <span className={classes.text}>
        <h1>
          <RouterLink to='/'>Coolest Matrices</RouterLink>
        </h1>
        {page && (
          <>
            <span>/</span>
            <span>{page}</span>
          </>
        )}
      </span>
      <a href='https://github.com/NitzanHen/matrices'>
        <Github className={classes.github} />
      </a>
    </div >
  );
};
