// packages/frontend-react/src/pages/CrossProductPage.tsx
import { crossProduct, generateVector } from '@matrices/common';
import React, { useEffect } from 'react';

import { Equal } from '../components/svg/Equal';
import { Multiply as Cross } from '../components/svg/Multiply';
import { Matrix } from '../matrix/Matrix';

import { useMatrix } from '../matrix/useMatrix';

import { OperationPage } from './OperationPage';

export const CrossProductPage: React.VFC = () => {
  const vector1 = useMatrix({
    label: 'u',
    unresizable: true,
    defaultCells: [generateVector(3, () => null)]
  });

  const vector2 = useMatrix({
    label: 'v',
    unresizable: true,
    defaultCells: [generateVector(3, () => null)]
  });

  const product = useMatrix({
    label: 'u×v',
    unresizable: true,
    readonly: true,
    defaultCells: [generateVector(3, () => null)]
  });

  const { setCells: setProductCells, clear: clearProduct } = product;
  useEffect(() => {
    const [v1] = vector1.cells;
    const [v2] = vector2.cells;

    const result = crossProduct(v1, v2);
    if (result.ok) {
      setProductCells([result.value]);
    } else {
      clearProduct();
    }
  }, [vector1.cells, vector2.cells, setProductCells, clearProduct]);

  return (
    <OperationPage>
      <Matrix {...vector1.toProps()} />
      <Cross />
      <Matrix {...vector2.toProps()} />
      <Equal />
      <Matrix {...product.toProps()} />
    </OperationPage>
  );
};

// packages/frontend-angular/src/app/pages/cross-product-page/cross-product-page.component.ts
import { Component, OnInit } from '@angular/core';
import { crossProduct, generateVector } from '@matrices/common';
import { zip } from 'rxjs';

import { Matrix } from 'src/Matrix';

@Component({
  selector: 'app-cross-product-page',
  templateUrl: './cross-product-page.component.html',
  styles: []
})
export class CrossProductPageComponent implements OnInit {
  vector1 = new Matrix({ unresizable: true, defaultCells: [generateVector(3)] });
  vector2 = new Matrix({ unresizable: true, defaultCells: [generateVector(3)] });

  product = new Matrix({ unresizable: true, readonly: true, defaultCells: [generateVector(3)] });

  constructor() {}

  ngOnInit(): void {
    zip(this.vector1.cellsObserver, this.vector2.cellsObserver).subscribe(([v1, v2]) => {
      const [u] = v1;
      const [v] = v2;

      const result = crossProduct(u, v);
      if (result.ok) {
        this.product.cells = [result.value];
      } else {
        this.product.clear();
      }
    });
  }
}

<app-operation-page>
  <app-matrix [m]="vector1">
    <ng-container label>u</ng-container>
  </app-matrix>

  <app-multiply></app-multiply>

  <app-matrix [m]="vector2">
    <ng-container label>v</ng-container>
  </app-matrix>

  <app-equal></app-equal>

  <app-matrix [m]="product">
    <ng-container label>u×v</ng-container>
  </app-matrix>
</app-operation-page>
