// packages/frontend-react/src/matrix/Matrix.tsx
import React, { ReactNode, useCallback, useMemo, FocusEvent } from 'react';
import clsx from 'clsx';
import { createUseStyles } from 'react-jss';
import { CellValue, generateMatrix, Matrix as MathMatrix } from '@matrices/common';

import { BaseComponentProps } from '../types';
import { Multiply } from '../components/svg/Multiply';

import { EmbeddedCell } from './EmbeddedCell';

interface MatrixDimensions {
  numRows: number;
  numColumns: number;
}

const useStyles = createUseStyles(
  {
    root: {
      width: 'max-content',
      height: 'max-content',
      position: 'relative'
    },

    matrix: ({ numRows, numColumns }: MatrixDimensions) => ({
      display: 'grid',
      gridTemplateRows: `repeat(${numRows}, 100px)`,
      gridTemplateColumns: `repeat(${numColumns}, 100px)`,
      rowGap: 8,
      columnGap: 8,

      '& > $cell': {
        width: '100%',
        height: '100%'
      }
    }),
    cell: {},
    label: {
      position: 'absolute',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      bottom: 'calc(100% + 8px)',
      left: 0,
      right: 0,
      zIndex: 100,
      textAlign: 'center',
      fontSize: 28,
      color: 'var(--color-primary)',
      '& > :not(:last-child)': {
        marginRight: 8
      },
    },

    dimensionInput: {
      display: 'inline-block',
      background: 'none',
      border: 'none',
      width: '0.8em',
      borderBottom: '1px solid var(--color-primary)',
      color: 'var(--color-primary)',
      transition: 'all 100ms ease-in-out',
      textAlign: 'center',
      fontSize: '0.6em',

      '&:focus-visible': {
        outline: 'none',
      },
      '&:focus': {
        borderColor: 'var(--color-light)'
      }
    },

    dimensionsForm: {
      display: 'inline-flex',
      alignItems: 'flex-end',
      backgroundColor: 'var(--background-light)',
      padding: '2px 6px 4px 6px',
      borderRadius: 4,

      '& > svg': {
        width: '0.7em',
        height: '0.7em',
        fill: 'var(--color-primary)'
      }
    },
  },
  { name: 'matrix' }
);

export interface MatrixProps extends BaseComponentProps {
  cells: MathMatrix;
  onChange: (row: number, column: number, value: CellValue) => void;
  onNumRowsChanged: (numRows: number) => void,
  onNumColumnsChanged: (numColumns: number) => void,
  setFocus: (row: number, column: number) => void;
  readonly?: boolean;
  unresizable?: boolean;
  gridRef?: React.Ref<HTMLDivElement>;
  label?: ReactNode;
}

/**
 * A matrix - i.e. a grid of cells.
 * The intended use for this component is with the `useMatrix` hook.
 */
export const Matrix: React.VFC<MatrixProps> = ({
  cells,
  unresizable = false,
  readonly = false,
  onChange,
  onNumRowsChanged,
  onNumColumnsChanged,
  setFocus,
  className,
  style,
  gridRef,
  label
}) => {
  const [numRows, numColumns] = [cells.length, cells[0].length];

  const onChangeHandlers = useMemo(
    () =>
      generateMatrix(numRows, numColumns, (i, j) => (value: CellValue) => onChange(i, j, value)),
    [numRows, numColumns, onChange]
  );

  const classes = useStyles({ numRows, numColumns });

  const handleNumRowsChange = useCallback((e: FocusEvent<HTMLInputElement>) => {
    e.preventDefault();
    e.stopPropagation();
    const value = parseInt(e.target.value);
    if (!isNaN(value)) {
      onNumRowsChanged(value)
    }
  }, [onNumRowsChanged]);

  const handleNumColumnsChange = useCallback((e: FocusEvent<HTMLInputElement>) => {
    e.preventDefault()
    e.stopPropagation()
    const value = parseInt(e.target.value);
    if (!isNaN(value)) {
      onNumColumnsChanged(value)
    }
  }, [onNumColumnsChanged]);

  return (
    <div className={clsx(classes.root, className)}>
      <div className={classes.label}>
        <span>{label}</span>
        {!unresizable && (
          <article className={classes.dimensionsForm}>
            <input
              tabIndex={-1}
              name='num-rows'
              onChange={handleNumRowsChange}
              className={classes.dimensionInput}
              defaultValue={numRows}
            />
            <Multiply />
            <input
              tabIndex={-1}
              name='num-columns'
              onChange={handleNumColumnsChange}
              className={classes.dimensionInput}
              defaultValue={numColumns}
            />
          </article>
        )}

      </div>
      <div className={classes.matrix} style={style} ref={gridRef}>
        {cells.flatMap((row, i) =>
          row.map((value, j) => (
            <EmbeddedCell
              className={classes.cell}
              row={i}
              column={j}
              key={`(${i},${j})`}
              label={`(${i},${j})`}
              value={value}
              onChange={onChangeHandlers[i][j]}
              readonly={readonly}
              setFocus={setFocus}
            />
          ))
        )}
      </div>
    </div>
  );
};

// packages/frontend-svelte/src/components/matrix/Matrix.svelte
<script lang="ts">
  import type { Matrix } from '@matrices/common';
  import type { Writable } from 'svelte/store';
  import { range, stringifyStyles } from '../../utils';
  import Multiply from '../svg/Multiply.svelte';
  import Cell from './Cell.svelte';

  export let cells: Writable<Matrix>;
  export let readonly: boolean = false;
  export let unresizable: boolean = false;

  export let gridRef: Writable<HTMLDivElement | null>;
  export let setFocus: (row: number, column: number) => void;

  /**
   * Naturally, these would be on:event listeners.
   * However, since they are created in `useMatrix` and passed directly to this component,
   * setting them up as event listeners would add redundant work, and they are passed as props instead.
   */
  export let onNumRowsChanged: (newNumRows: number) => void;
  export let onNumColumnsChanged: (newNumColumns: number) => void;

  $: numRows = $cells.length;
  $: numColumns = $cells[0].length;

  type ChangeEvent = Event & { currentTarget: EventTarget & HTMLInputElement };
  $: handleNumRowsChange = (e: ChangeEvent) => {
    const value = e.currentTarget.value;
    const parsed = parseInt(value);

    if (!isNaN(parsed)) {
      onNumRowsChanged(parsed);
    }
  };
  $: handleNumColumnsChange = (e: ChangeEvent) => {
    const value = e.currentTarget.value;
    const parsed = parseInt(value);

    if (!isNaN(parsed)) {
      onNumColumnsChanged(parsed);
    }
  };

  $: matrixStyles = stringifyStyles({
    'grid-template-rows': `repeat(${numRows}, 100px)`,
    'grid-template-columns': `repeat(${numColumns}, 100px)`
  });
</script>

<div class="root">
  <div class="label">
    <span><slot name="label" /></span>
    {#if !unresizable}
      <article class="dimensions">
        <input tabindex={-1} type="number" value={numRows} on:input={handleNumRowsChange} />
        <Multiply />
        <input tabindex={-1} type="number" value={numColumns} on:input={handleNumColumnsChange} />
      </article>
    {/if}
  </div>

  <div class="matrix" bind:this={$gridRef} style={matrixStyles}>
    {#each range(0, numRows) as row}
      {#each range(0, numColumns) as column}
        <Cell
          {row}
          {column}
          {readonly}
          key={`(${row}, ${column})`}
          {setFocus}
          bind:value={$cells[row][column]}
        >
          <svelte:fragment slot="label">{`(${row},${column})`}</svelte:fragment>
        </Cell>
      {/each}
    {/each}
  </div>
</div>

<style>
  .root {
    width: max-content;
    height: max-content;
    position: relative;
  }

  .label {
    position: absolute;
    left: 0;
    right: 0;
    bottom: calc(100% + 8px);

    display: flex;
    align-items: center;
    justify-content: center;
    text-align: center;
    font-size: 28px;
    z-index: 100;
    color: var(--color-primary);
  }
  .label > :not(:last-child) {
    margin-right: 8px;
  }

  .dimensions {
    display: inline-flex;
    align-items: flex-end;

    padding: 2px 6px 4px 6px;
    background-color: var(--background-light);
    border-radius: 4px;
  }

  .dimensions > input {
    display: inline-block;
    background: none;
    border: none;
    border-bottom: 1px solid var(--color-primary);
    color: var(--color-primary);
    transition: all 100ms ease-in-out;
    text-align: center;
    font-size: 0.6em;
    width: 0.8em;
  }

  .dimensions > input:focus-visible {
    outline: none;
  }
  .dimensions > input:focus {
    border-color: var(--color-light);
  }

  .dimensions > :global(svg) {
    width: 0.7em;
    height: 0.7em;
    fill: var(--color-primary);
  }

  .matrix {
    display: grid;
    row-gap: 8px;
    column-gap: 8px;
  }
</style>
