// packages/frontend-react/src/pages/DotProductPage.tsx
import { dotProduct, generateVector } from '@matrices/common';
import React, { useEffect } from 'react';

import { Dot } from '../components/svg/Dot';

import { Equal } from '../components/svg/Equal';
import { Matrix } from '../matrix/Matrix';

import { useMatrix } from '../matrix/useMatrix';

import { OperationPage } from './OperationPage';

export const DotProductPage: React.VFC = () => {
  const vector1 = useMatrix({
    label: 'u',
    unresizable: true,
    defaultCells: [generateVector(3)]
  });

  const vector2 = useMatrix({
    label: 'v',
    unresizable: true,
    defaultCells: [generateVector(3)]
  });

  const product = useMatrix({
    label: 'u·v',
    readonly: true,
    unresizable: true,
    defaultCells: [[null]]
  });

  const { setCells: setProductCells, clear: clearProduct } = product;
  useEffect(() => {
    const [v1] = vector1.cells;
    const [v2] = vector2.cells;

    const result = dotProduct(v1, v2);
    if (result.ok) {
      setProductCells([[result.value]]);
    } else {
      clearProduct();
    }
  }, [vector1.cells, vector2.cells, clearProduct, setProductCells]);

  return (
    <OperationPage>
      <Matrix {...vector1.toProps()} />
      <Dot />
      <Matrix {...vector2.toProps()} />
      <Equal />
      <Matrix {...product.toProps()} />
    </OperationPage>
  );
};

// packages/frontend-angular/src/app/pages/dot-product-page/dot-product-page.component.ts
import { Component, OnInit } from '@angular/core';
import { dotProduct, generateVector } from '@matrices/common';
import { zip } from 'rxjs';

import { Matrix } from 'src/Matrix';

@Component({
  selector: 'app-dot-product-page',
  templateUrl: './dot-product-page.component.html',
  styles: []
})
export class DotProductPageComponent implements OnInit {
  vector1 = new Matrix({ unresizable: true, defaultCells: [generateVector(3)] });
  vector2 = new Matrix({ unresizable: true, defaultCells: [generateVector(3)] });

  product = new Matrix({ unresizable: true, readonly: true, defaultCells: [[null]] });

  constructor() {}

  ngOnInit(): void {
    zip(this.vector1.cellsObserver, this.vector2.cellsObserver).subscribe(([v1, v2]) => {
      const [u] = v1;
      const [v] = v2;

      const result = dotProduct(u, v);
      if (result.ok) {
        this.product.cells = [[result.value]];
      } else {
        this.product.clear();
      }
    });
  }
}

<app-operation-page>
  <app-matrix [m]="vector1">
    <ng-container label>u</ng-container>
  </app-matrix>

  <app-dot></app-dot>

  <app-matrix [m]="vector2">
    <ng-container label>v</ng-container>
  </app-matrix>

  <app-equal></app-equal>

  <app-matrix [m]="product">
    <ng-container label>u·v</ng-container>
  </app-matrix>
</app-operation-page>
