// packages/frontend-angular/src/app/pages/matrix-determinant-page/matrix-determinant-page.component.ts
import { Component, OnInit } from '@angular/core';
import { determinant } from '@matrices/common';

import { Matrix } from 'src/Matrix';

@Component({
  selector: 'app-matrix-determinant-page',
  templateUrl: './matrix-determinant-page.component.html',
  styles: []
})
export class MatrixDeterminantPageComponent implements OnInit {
  matrix1 = new Matrix();
  det = new Matrix({ unresizable: true, readonly: true, defaultCells: [[null]] });

  constructor() {}

  ngOnInit() {
    //Listen to the cells of both observables, and update cell accordingly.
    this.matrix1.cellsObserver.subscribe(cells => {
      const result = determinant(cells);
      if (result.ok) {
        this.det.cells = [[result.value]];
      } else {
        this.det.clear();
      }
    });
  }
}

<app-operation-page>
  <app-matrix [m]="matrix1">
    <ng-container label>A</ng-container>
  </app-matrix>

  <app-right-arrow></app-right-arrow>

  <app-matrix [m]="det">
    <ng-container label>|A|</ng-container>
  </app-matrix>

</app-operation-page>

// packages/frontend-vue/src/pages/MatrixDeterminantPage.vue
<template>
  <OperationPage>
    <Matrix v-bind="props1" v-on="handlers1">
      <template v-slot:label>A</template>
    </Matrix>
    <RightArrow></RightArrow>
    <Matrix v-bind="detProps" v-on="detHandlers">
      <template v-slot:label>|A|</template>
    </Matrix>
  </OperationPage>
</template>

<script lang='ts'>
import { defineComponent, watchEffect } from "@vue/runtime-core";
import OperationPage from '../pages/OperationPage.vue';
import Matrix from "../components/matrix/Matrix.vue";
import { useMatrix } from "../composable/useMatrix";
import { determinant } from "@matrices/common";
import RightArrow from "../components/svg/RightArrow.vue";

export default defineComponent({
  name: 'matrix-determinant-page',
  components: {
    OperationPage,
    Matrix,
    RightArrow
  },

  setup() {
    const matrix = useMatrix();

    const det = useMatrix({ readonly: true, unresizable: true, defaultCells: [[null]] });

    watchEffect(() => {
      const result = determinant(matrix.cells.value);
      if (result.ok) {
        det.cells.value = [[result.result]];
      }
      else {
        det.clear();
      }
    })

    return {
      props1: matrix.props,
      handlers1: matrix.eventHandlers,
      detProps: det.props,
      detHandlers: det.eventHandlers
    }
  }
})
</script>
