// packages/frontend-angular/src/app/pages/matrix-transpose-page/matrix-transpose-page.component.ts
import { Component, OnInit } from '@angular/core';
import { transpose } from '@matrices/common';

import { Matrix } from 'src/Matrix';

@Component({
  selector: 'app-matrix-transpose-page',
  templateUrl: './matrix-transpose-page.component.html',
  styles: []
})
export class MatrixTransposePageComponent implements OnInit {
  matrix1 = new Matrix();
  transposed = new Matrix({ unresizable: true, readonly: true });

  constructor() {}

  ngOnInit() {
    //Listen to the cells of both observables, and update cell accordingly.
    this.matrix1.cellsObserver.subscribe(cells => {
      const result = transpose(cells);
      if (result.ok) {
        this.transposed.cells = result.value;
      } else {
        this.transposed.clear();
      }
    });
  }
}

<app-operation-page>
  <app-matrix [m]="matrix1">
    <ng-container label>A</ng-container>
  </app-matrix>

  <app-right-arrow></app-right-arrow>

  <app-matrix [m]="transposed">
    <ng-container label>A<sup>t</sup></ng-container>
  </app-matrix>

</app-operation-page>

// packages/frontend-vue/src/pages/MatrixTransposePage.vue
<template>
  <OperationPage>
    <Matrix v-bind="props1" v-on="handlers1">
      <template v-slot:label>A</template>
    </Matrix>
    <RightArrow></RightArrow>
    <Matrix v-bind="transposedProps" v-on="transposedHandlers">
      <template v-slot:label>A<sup>t</sup></template>
    </Matrix>
  </OperationPage>
</template>

<script lang='ts'>
import { defineComponent, watchEffect } from "@vue/runtime-core";
import OperationPage from '../pages/OperationPage.vue';
import Matrix from "../components/matrix/Matrix.vue";
import { useMatrix } from "../composable/useMatrix";
import { transpose } from "@matrices/common";
import RightArrow from "../components/svg/RightArrow.vue";

export default defineComponent({
  name: 'matrix-transpose-page',
  components: {
    OperationPage,
    Matrix,
    RightArrow
  },

  setup() {
    const matrix = useMatrix();

    const transposed = useMatrix({ unresizable: true, readonly: true });

    watchEffect(() => {
      const result = transpose(matrix.cells.value);
      if (result.ok) {
        transposed.cells.value = result.value;
      }
      else {
        transposed.clear();
      }
    })

    return {
      props1: matrix.props,
      handlers1: matrix.eventHandlers,
      transposedProps: transposed.props,
      transposedHandlers: transposed.eventHandlers
    }
  }
})
</script>
