// packages/frontend-svelte/src/pages/MatrixTransposePage.svelte
<script>
  import { transpose } from '@matrices/common';

  import Matrix from '../components/matrix/Matrix.svelte';
  import RightArrow from '../components/svg/RightArrow.svelte';
  import { useMatrix } from '../store/useMatrix';

  import OperationPage from './OperationPage.svelte';

  let { cells: cells1, props: props1 } = useMatrix();

  let {
    cells: transposeCells,
    props: transposeProps,
    clear: clearTranspose
  } = useMatrix({ readonly: true, unresizable: true });

  $: {
    const result = transpose($cells1);
    if (result.ok) {
      transposeCells.set(result.value);
    } else {
      clearTranspose();
    }
  }
</script>

<OperationPage>
  <Matrix {...$props1}>
    <svelte:fragment slot="label">A</svelte:fragment>
  </Matrix>
  <RightArrow />
  <Matrix {...$transposeProps}>
    <svelte:fragment slot="label">A<sup>t</sup></svelte:fragment>
  </Matrix>
</OperationPage>

// packages/frontend-vue/src/pages/MatrixTransposePage.vue
<template>
  <OperationPage>
    <Matrix v-bind="props1" v-on="handlers1">
      <template v-slot:label>A</template>
    </Matrix>
    <RightArrow></RightArrow>
    <Matrix v-bind="transposedProps" v-on="transposedHandlers">
      <template v-slot:label>A<sup>t</sup></template>
    </Matrix>
  </OperationPage>
</template>

<script lang='ts'>
import { defineComponent, watchEffect } from "@vue/runtime-core";
import OperationPage from '../pages/OperationPage.vue';
import Matrix from "../components/matrix/Matrix.vue";
import { useMatrix } from "../composable/useMatrix";
import { transpose } from "@matrices/common";
import RightArrow from "../components/svg/RightArrow.vue";

export default defineComponent({
  name: 'matrix-transpose-page',
  components: {
    OperationPage,
    Matrix,
    RightArrow
  },

  setup() {
    const matrix = useMatrix();

    const transposed = useMatrix({ unresizable: true, readonly: true });

    watchEffect(() => {
      const result = transpose(matrix.cells.value);
      if (result.ok) {
        transposed.cells.value = result.value;
      }
      else {
        transposed.clear();
      }
    })

    return {
      props1: matrix.props,
      handlers1: matrix.eventHandlers,
      transposedProps: transposed.props,
      transposedHandlers: transposed.eventHandlers
    }
  }
})
</script>
