// packages/frontend-react/src/pages/WelcomePage.tsx
import React from "react";
import { createUseStyles } from "react-jss";
import calculator from "../calculator.svg";
import { Link } from "../components/Link";

const useStyles = createUseStyles(
  {
    root: {
      width: "100%",
      height: "100%",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    content: {
      textAlign: "center",
      display: "flex",
      alignItems: "center",
      flexDirection: "column",
      "& > img": {
        maxHeight: "40vh",
        maxWidth: "40vh",
      },
    },
    actions: {
      marginTop: 40,
      width: '100%',
      overflow: 'hidden',
      display: "flex",

      "& > span": {
        display: "block",
        width: 1,
        flex: "0 0 auto",
        backgroundColor: "var(--background-dark)",
        opacity: 0.3,
        margin: "0 24px",
      },

      "& > div": {
        flex: "1 1 50%",
        display: "grid",
        padding: 8,
        gridTemplateColumns: "1fr 1fr",
        gridTemplateRows: "1fr 1fr",
        columnGap: 16,
        rowGap: 16,
      },
    },
  },
  { name: "welcome" }
);

export const WelcomePage: React.VFC = () => {
  const classes = useStyles();

  return (
    <div className={classes.root}>
      <div className={classes.content}>
        <img src={calculator} />
        <h1>Welcome</h1>
        <p>select an operation to get started</p>
        <div className={classes.actions}>
          <div>
            <Link to='/matrix/sum'>Matrix addition</Link>
            <Link to='/matrix/product'>Matrix multiplication</Link>
            <Link to='/matrix/transpose'>Matrix transpose</Link>
            <Link to='/matrix/determinant'>Matrix determinant</Link>
          </div>
          <span />
          <div>
            <Link to='/vector/dot'>Dot product</Link>
            <Link to='/vector/cross'>Cross product</Link>
          </div>
        </div>
      </div>
    </div>
  );
};

// packages/frontend-vue/src/pages/WelcomePage.vue
  <template>
  <div class="welcome-page-root">
    <div class="content">
      <img :src="calculator" />
      <h1>Welcome!</h1>
      <p>select an operation to get started</p>
      <div class="actions">
        <h2>Matrix</h2>
        <span></span>
        <h2>Vector</h2>

        <div>
          <HomeLink to="/matrix/sum" class="link">Matrix addition</HomeLink>
          <HomeLink to="/matrix/product" class="link">Matrix multiplication</HomeLink>
          <HomeLink to="/matrix/transpose" class="link">Matrix transpose</HomeLink>
          <HomeLink to="/matrix/determinant" class="link">Matrix determinant</HomeLink>
        </div>
        <span class="divider"></span>
        <div>
          <HomeLink to="/vector/dot" class="link">Dot product</HomeLink>
          <HomeLink to="/vector/cross" class="link">Cross product</HomeLink>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import calculator from '../assets/calculator.svg'
import HomeLink from "../components/HomeLink.vue";

export default defineComponent({
  name: 'welcome-page',
  components: {
    HomeLink
  },
  setup() {
    return { calculator }
  }
})
</script>

<style scoped>
.welcome-page-root {
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
}

.content {
  display: flex;
  flex-direction: column;
  align-items: center;

  text-align: center;
}
.content > img {
  max-width: 40vh;
  max-height: 40vh;
}

.actions {
  width: 100%;

  display: grid;
  grid-template-rows: auto auto;
  row-gap: 16px;
  grid-template-columns: 1fr 1px 1fr;
  column-gap: 16px;

  overflow: hidden;
  margin-top: 40px;
}
.actions > div {
  flex: 1 1 50%;
  padding: 8px;

  display: grid;
  grid-template-rows: 1fr 1fr;
  row-gap: 16px;
  grid-template-columns: 1fr 1fr;
  column-gap: 16px;
}

.divider {
  display: block;
  width: 1px;
  flex: 0 0 auto;

  background-color: var(--background-dark);
  opacity: 0.3;
}

.link {
  max-width: 120px;
}
</style>
