// packages/frontend-vue/src/components/HomeLink.vue
<template>
  <router-link v-bind="props" class="home-link">
    <slot></slot>
  </router-link>
</template>

<script lang='ts'>
import { defineComponent } from "@vue/runtime-core";
import { RouterLinkProps } from "vue-router";


/** A styled wrapper around Vue router's `router-link` */
export default defineComponent((props: RouterLinkProps) => ({
  props
}))
</script>

<style scoped>
.home-link {
  display: inline-flex;
  align-items: center;
  justify-content: center;

  text-decoration: none;
  border: none;
  cursor: pointer;

  border-radius: 4px;
  padding: 8px 12px;
  font-size: 16px;

  background-color: var(--background-light);
  color: "var(--color-primary)";
}
</style>

// packages/frontend-svelte/src/components/HomeLink.svelte
<script lang="ts">
  import { link } from 'svelte-routing';

  export let to: string;

  export let style: string;
</script>

<a use:link href={to} class="link" {style}>
  <slot />
</a>

<style>
  .link {
    cursor: pointer;
    border: none;
    padding: 8px 12px;
    font-size: 16px;
    border-radius: 4px;
    text-decoration: none;

    display: inline-flex;
    align-items: center;
    justify-content: center;

    background-color: var(--background-light);
    color: var(--color-primary);
  }
</style>
