// packages/frontend-vue/src/App.vue
<template>
  <div class="root">
    <TopBar :pagename="pagename"></TopBar>
    <main>
      <router-view></router-view>
    </main>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { useRoute } from 'vue-router';
import TopBar from './components/TopBar.vue';

export default defineComponent({
  name: 'App',
  components: {
    TopBar
  },

  setup() {
    const route = useRoute();

    const pagename = route.path.substring(1);
    return { pagename }
  }
})
</script>

<style>
:root {
  --background-light: #f0efff;
  --background-dark: #3a3768;
  --background-result: #3a3768cd;
  --color-primary: #3f3c72;
  --color-light: #6c63ff;
  --color-result: #f0efff;
}
</style>
<style scoped>
.root {
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  color: var(--color-primary);
}

.root > main {
  flex: 1 0 auto;
}
</style>

// packages/frontend-react/src/App.tsx
import clsx from "clsx";
import React from "react";
import { createUseStyles } from "react-jss";
import { Route, Switch } from "react-router";
import { TopBar } from "./components/TopBar";
import { WelcomePage } from "./components/WelcomePage";

const useStyles = createUseStyles(
  {
    colorDefs: {
      "--background-light": "#F0EFFF",
      "--background-dark": "#3A3768",
      "--color-primary": "#3F3C72",
    },

    root: {
      width: "100%",
      height: "100%",
      display: "flex",
      flexDirection: "column",

      "& > main": {
        flex: "1 0 auto",
      },
      color: 'var(--color-primary)'
    },
  },
  { name: "app" }
);

function App() {
  const classes = useStyles();

  return (
    <div className={clsx(classes.root, classes.colorDefs)}>
      <TopBar />
      <main>
        <Switch>
          <Route path="/" exact>
            <WelcomePage />
          </Route>
        </Switch>
      </main>
    </div>
  );
}

export default App;
